name: 'dbt_to_clickhouse'
version: '1.0.0'
config-version: 2
 
profile: 'dbt_to_clickhouse'
 
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
 
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  dbt_to_clickhouse:
    staging:
      +materialized: view
    marts:
      +materialized: table
 
seeds:
  dbt_to_clickhouse:
    +delimiter: ";"
    +quote_columns: false
 
    protocols:
      +column_types:
          Report_ID: String
          Household_ID: String
          Visit_Year: String
          Visit_Date: String
          Building_Type: String
          Building_HousingUnits: String
          Building_ConstructionYear: String
          Building_ConstructionYear_Interval: String
          Building_Renovated_Windows: String
          Building_Renovated_Roof: String
          Building_Renovated_Walls: String
          Building_Renovated_Floor: String
          Building_FloorAreaHeated_Total: String
          Building_FloorAreaHeated_Basement: String
          Building_FloorAreaHeated_GroundFloor: String
          Building_FloorAreaHeated_FirstFloor: String
          Building_FloorAreaHeated_SecondFloor: String
          Building_FloorAreaHeated_TopFloor: String
          Building_FloorAreaHeated_AdditionalAreasPlanned: String
          Building_FloorAreaHeated_AdditionalAreasPlannedSize: String
          Building_Residents: String
          Building_PVSystem_Available: String
          Building_PVSystem_Size: String
          Building_ElectricVehicle_Available: String
          HeatPump_Installation_Type: String
          HeatPump_Installation_Year: String
          HeatPump_Installation_Manufacturer: String
          HeatPump_Installation_Model: String
          HeatPump_Installation_HeatingCapacity: String
          HeatPump_Installation_Refrigerant_Type: String
          HeatPump_Installation_Refrigerant_Content: String
          HeatPump_Installation_Normpoint: String
          HeatPump_Installation_Normpoint_COP: String
          HeatPump_Installation_Normpoint_ElectricPower: String
          HeatPump_Installation_Normpoint_HeatingPower: String
          HeatPump_Installation_Location: String
          HeatPump_Installation_InternetConnection: String
          HeatPump_Installation_ControllerNotAccessible: String
          HeatDistribution_System_Radiators: String
          HeatDistribution_System_FloorHeating: String
          HeatDistribution_System_ThermostaticValve: String
          HeatDistribution_System_BufferTankAvailable: String
          DHW_Production_ByHeatPump: String
          DHW_Production_ByElectricWaterHeater: String
          DHW_Production_BySolar: String
          DHW_Production_ByHeatPumpBoiler: String
          DHW_ByHeatPump_TimeInterval: String
          DHW_Production_TypeOfHeating: String
          DHW_Production_Residents: String
          DHW_Circulation_NotInUse: String
          DHW_Circulation_ByTraceHeating: String
          DHW_Circulation_ByCirculationPump: String
          DHW_Circulation_SwitchedByTimer: String
          DHW_Sterilization_Available: String
          DHW_Sterilization_Active: String
          HeatPump_Clean: String
          HeatPump_BasicFunctionsOkay: String
          HeatPump_TechnicallyOkay: String
          HeatPump_ElectricityConsumption_YearlyEstimated: String
          HeatPump_ElectricityConsumption_Categorization: String
          HeatPump_Installation_CorrectlyPlanned: String
          HeatPump_Installation_IncorrectlyPlanned_Categorization: String
          HeatPump_AirSource_AirDuctsDistanceOkay: String
          HeatPump_AirSource_AirDuctsFree: String
          HeatPump_AirSource_AirDuctsCleaningRequired: String
          HeatPump_AirSource_AirDuctsDrainOkay: String
          HeatPump_AirSource_EvaporatorClean: String
          HeatPump_GroundSource_BrineCircuit_Length: String
          HeatPump_GroundSource_BrineCircuit_Depth: String
          HeatPump_GroundSource_BrineCircuit_NumberOfHoles: String
          HeatPump_GroundSource_BrineCircuit_CoolingCapacity: String
          HeatPump_GroundSource_BrineCircuit_AntiFreezeExists: String
          HeatPump_GroundSource_CurrentPressure: String
          HeatPump_GroundSource_CurrentPressure_Okay: String
          HeatPump_GroundSource_CurrentTemperature: String
          HeatPump_GroundSource_CurrentTemperature_Okay: String
          HeatPump_HeatingCurveSetting_TooHigh_BeforeVisit: String
          HeatPump_HeatingCurveSetting_Changed: String
          HeatPump_HeatingCurveSetting_Outside20_BeforeVisit: String
          HeatPump_HeatingCurveSetting_Outside0_BeforeVisit: String
          HeatPump_HeatingCurveSetting_OutsideMinus8_BeforeVisit: String
          HeatPump_HeatingCurveSetting_Outside20_AfterVisit: String
          HeatPump_HeatingCurveSetting_Outside0_AfterVisit: String
          HeatPump_HeatingCurveSetting_OutsideMinus8_AfterVisit: String
          HeatPump_HeatingLimitSetting_TooHigh_BeforeVisit: String
          HeatPump_HeatingLimitSetting_Changed: String
          HeatPump_HeatingLimitSetting_BeforeVisit: String
          HeatPump_HeatingLimitSetting_AfterVisit: String
          HeatPump_NightSetbackSetting_Activated_BeforeVisit: String
          HeatPump_NightSetbackSetting_Activated_AfterVisit: String
          DHW_TemperatureSetting_Categorization: String
          DHW_TemperatureSetting_Changed: String
          DHW_TemperatureSetting_BeforeVisit: String
          DHW_TemperatureSetting_AfterVisit: String
          DHW_Storage_LastDescaling_TooLongAgo: String
          DHW_Storage_LastDescaling_Year: String
          HeatDistribution_ExpansionTank_Pressure_Categorization: String
          HeatDistribution_ExpansionTank_Pressure_Actual: String
          HeatDistribution_ExpansionTank_Pressure_Target: String
          HeatDistribution_ExpansionTank_SystemHeight: String
          HeatDistribution_Circulation_PumpStagePosition_Changed: String
          HeatDistribution_Circulation_PumpStagePosition_BeforeVisit: String
          HeatDistribution_Circulation_PumpStagePosition_AfterVisit: String
          HeatDistribution_Recommendation_InsulatePipes: String
          HeatDistribution_Recommendation_InstallThermostaticValve: String
          HeatDistribution_Recommendation_InstallRPMValve: String
 
    households:
      +column_types:
        Household_ID: String