name: 'dbt_to_clickhouse'
version: '1.0.0'
config-version: 2
 
# Verknüpfung zur profiles.yml
profile: 'dbt_to_clickhouse'
 
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
 
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
 
models:
  dbt_to_clickhouse:
    # Staging-Modelle als View: kein zusätzlicher Speicherverbrauch für Zwischenschritte
    staging:
      +materialized: view
    # Finale Dimensions- und Faktentabellen des Star Schemas als Table
    marts:
      +materialized: table
 
seeds:
  dbt_to_clickhouse:
    # Globale Einstellungen für alle 1308 Dateien
    +delimiter: ";"
    +quote_columns: false
 
    # Fix für protocols (verhindert den Date-Error bei unsauberen Zeilen)
    protocols:
      +column_types:
        Report_ID: String
        Household_ID: String
        Visit_Date: String
        Visit_Year: String
 
    # Fix für households (Semikolon-Trennung sicherstellen)
    households:
      +column_types:
        Household_ID: String